### ISSUE TITLE
select2 + czMore problem

### ISSUE THREAD

**Issue by kindaniel** [cozeit/czMore#6] opened 2019-06-12 18:52 UTC
Select2 new fields for CzMore is not working. in the field that is not created with czMore is working, the add on method onAdd does not work. Any idea?

**Comment by yatabani** [comment] 2019-07-11 06:28
You need to hookup select2, on the onAdd event

**Comment by yatabani** [comment] 2019-07-11 06:34
Hope this helps
```
$("#czContainer").czMore({
        onAdd: function() {
            $("input[id$='_suffex']").select2();
        }
});
```

**Comment by yatabani** [comment] 2019-07-11 06:43
duplicate of issue number #4

**Comment by yatabani** [comment] 2019-07-14 10:34
please refer to http://yatabani.com/Integrating-Select2-with-czMore/

**Closed by yatabani** 2019-07-14 10:34 UTC
